version: '3.7'
services:

  gate-simulator:
    build: .
    image: gate-simulator:1.0.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0.18
    volumes:
      - ./base/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./base/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

