version: '3.7'
services:

  gate-simulator:
    build: .
    image: gate-simulator:1.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0.18
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=base_mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

